[package]
name = "gametheory"
version = "0.0.0"
edition = "2021"

[dependencies]
eframe = { version = "0.26", features = ["wgpu", "wayland"], default-features = false }
rand = "0.8"
thiserror = "1.0"
